spring:
  datasource:
    url: jdbc:mysql://192.168.1.36:3306/test?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=TRUE&useSSL=true&serverTimezone=GMT%2b8
    username: root
    password: liuliu66
  application:
    name: zxx-boot-2
mybatis:
  type-aliases-package: com.zxx.boot.entity
  mapper-locations: mapper/*.xml
