spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        username: root
        password: liuliu66
        url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=TRUE&useSSL=true&serverTimezone=GMT%2b8
mybatis:
    type-aliases-package: com.zxx.order.entity
    mapper-locations: mapper/*.xml
#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
logging:
  level:
    org.springframework.cloud.netflix.feign: debug
env:
  dev
